### ISSUE TITLE
Rename this to RxActivityIndicator

### ISSUE THREAD

**Issue by AndrewSB** [RxSwiftCommunity/RxSwiftUtilities#1]
I think it's alright to make this a nice µ library. I'd actually prefer it 😄

**Comment by DivineDominion** [comment]
I second that! It misleadingly is named like this is similar to https://github.com/RxSwiftCommunity/RxSwiftExt

Do you have any concerns with this rename, like future plans @solidcell?

**Comment by solidcell** [comment]
No concerns about doing it.  I'm just occupied with other stuff atm.  PR is welcome if you want to change the name in the project first. pbxproj fun times. ;)

**Comment by AndrewSB** [comment]
haha, I've done it a couple times. an `mdfind "RxSwiftUtilities" -onlyin .` always comes in use to help me sanity check

PR incoming

**Comment by AndrewSB** [comment]
My bad on never finishing this, I'm sorry @solidcell!

**Comment by solidcell** [comment]
haha, no worries. I think I'm leaning toward keeping it a bit more generic anyway, so it might be for the best.
