### ISSUE TITLE
RxSwift 4.0.0 support

### ISSUE THREAD

**Issue by matthiasotto** [RxSwiftCommunity/RxSwiftUtilities#3]
Please add RxSwift 4 support.

**Comment by agrafiotisA** [comment]
Are there any news about this?

**Comment by bobgodwinx** [comment]
This is fixed in [Pull request 5](https://github.com/RxSwiftCommunity/RxSwiftUtilities/pull/5) enjoy :)

**Comment by xavier-lmk** [comment]
cocoapods can't find version 2.0.0

**Comment by bobgodwinx** [comment]
I think @solidcell has to trunk the pod. However the tag `2.0.0` is there. The [Pull request 5](https://github.com/RxSwiftCommunity/RxSwiftUtilities/pull/5) is bumping it to `2.1.0` and this can be tagged after merging b4 trunking.

**Comment by solidcell** [comment]
done
