### ISSUE TITLE
Deprecation Warning for Variable

### ISSUE THREAD

**Issue by ghost** [RxSwiftCommunity/RxSwiftUtilities#7]
ℹ️ [DEPRECATED] `Variable` is planned for future depreciation. Please consider `BehaviorRelay` as a replacement. Read more at: https://git.io/vNqvx
Permission granted: true

**Comment by solidcell** [comment]
Thanks @ios3. However, at the moment, as with the deprecation itself, the update path is unclear. Since it's not even a deprecation yet, I think it's wiser to wait to change anything for when there's more information available. There's no rush at the moment, but thanks for mentioning it.
